#!/usr/bin/env python3
import glob
import re
import sys

# ----------------------------------------------------------------------------
# This script scans for all generated PachisiLevel_<NAME>.h files and builds
# a pachisi_levels.h containing an array of PachisiLevelInfo structs, each
# pointing to the level data and its compile-time size.
# ----------------------------------------------------------------------------

LEVEL_RE = re.compile(
    r"static\s+const\s+struct\s+PachisiSquare\s+PachisiLevel_([A-Za-z0-9_]+)\s*\[\]"
)

HEADER = """#ifndef PACHISI_LEVELS_H
#define PACHISI_LEVELS_H

#include <stddef.h>          // for size_t
#include "pachisi_defines.h"
"""

STRUCT_START = """
struct PachisiLevelInfo {
    const PachisiSquare *level;
    size_t size;
};

static const struct PachisiLevelInfo pachisi_levels[] = {
"""

FOOTER = """};

#endif // PACHISI_LEVELS_H
"""

def find_generated_levels():
    """
    Scan *.h files, detect those generated by pachisi_map_builder.py,
    extract the NAME from PachisiLevel_<NAME> and return list of (NAME, filename).
    """
    results = []
    for fn in glob.glob("*.h"):
        with open(fn, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
        if not content.startswith("/* Generated by pachisi_map_builder.py */"):
            continue
        m = LEVEL_RE.search(content)
        if not m:
            print(f"Warning: no PachisiLevel_...[] found in {fn}", file=sys.stderr)
            continue
        name = m.group(1)
        results.append((name, fn))
    return sorted(results, key=lambda x: x[0])


def main():
    levels = find_generated_levels()
    if not levels:
        print("No generated .h files found.", file=sys.stderr)
        sys.exit(1)

    with open("pachisi_levels.h", "w", encoding="utf-8") as out:
        # Header and includes
        out.write(HEADER)
        for name, fn in levels:
            out.write(f"#include \"{fn}\"\n")
        out.write(STRUCT_START)

        # Emit each level info entry with compile-time size
        for name, _ in levels:
            out.write(
                f"    [PACHISI_LEVEL_{name}] = {{ .level = PachisiLevel_{name}, .size = sizeof(PachisiLevel_{name})/sizeof(*PachisiLevel_{name}) }},\n"
            )

        # Footer
        out.write(FOOTER)

    print(f"Wrote pachisi_levels.h with {len(levels)} entries.")

if __name__ == "__main__":
    main()
