static struct PachisiSquare PachisiLevel_the_first_loser[] =
{
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_CAVE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MONEY, .data = { 0, 0, 0 } },
    { .square = SQUARE_MUNCHER, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_LAND, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_WATER, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_CAVE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MONEY, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_LAND, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MUNCHER, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_CAVE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MONEY, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_WATER, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_LAND, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_WATER, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_CAVE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MONEY, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_WATER, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_LAND, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_NONE, .data = { 0, 0, 0 } },
    { .square = SQUARE_WILD_CAVE, .data = { 0, 0, 0 } },
    { .square = SQUARE_MUNCHER, .data = { 0, 0, 0 } },
    { .square = SQUARE_MONEY, .data = { 0, 0, 0 } },
    { .square = SQUARE_MOVE_FORWARD, .data = { 0, 0, 0 } },
    { .square = SQUARE_RANDOM, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
    { .square = SQUARE_DEATH, .data = { 0, 0, 0 } },
};

currentBoard = PachisiLevel_the_first_loser;
